version: '3.8'

services:
  streaming:
    build:
      context: .
      dockerfile: .ops/docker/app/Dockerfile
    ports:
      - "8000:8000"
      - "9988:9988"
    volumes:
      - .:/streaming_root
    depends_on:
      - database
    environment:
      ENV: "dev"
      LOGGER: "cli"
      MONGODB_URI: "mongodb://database:27017/streaming"
    command: ["sh", "-c", "go run ./cmd/main.go"]

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "/data/storage/mongodb:/data/db"

  mongodb-client:
    build:
      context: .
      dockerfile: .ops/docker/mongoclient/Dockerfile
    depends_on:
      - database
volumes:
  mongodb_data: