version: '3.8'

services:
  streaming:
    build:
      context: .
      dockerfile: .ops/docker/app/Dockerfile
    ports:
      - "8000:8000"
      - "9988:9988"
    volumes:
      - .:/streaming_root
    depends_on:
      - mongodb
    environment:
      # API
      API_VERSION_PREFIX: "/api/v1"
      RENDER_VERSION_PREFIX: ""
      STATIC_VERSION_PREFIX: ""
      # Server (http)
      RESOURCES_SERVER_HOST: "0.0.0.0"
      RESOURCES_SERVER_PORT: "8000"
      RESOURCES_SERVER_TRANSPORT_PROTOCOL: "tcp"
      # Server (websocket)
      STREAMING_SERVER_HOST: "0.0.0.0"
      STREAMING_SERVER_PORT: "9988"
      STREAMING_SERVER_TRANSPORT_PROTOCOL: "tcp"
      # Database
      MONGODB_URI: "mongodb://mongodb:27017/streaming"
      MONGO_DATABASE: "streaming"
      # Application
      UPLOADER_TYPE: "muiltipart_part"
      RESOURCE_FORM_FILENAME: "resource"
      MAX_UPLOADING_FILESIZE: "10000000000"
      IN_MEMORY_FILE_SIZE_THRESHOLD: 104857600
      ADMIN_CONTACT_EMAIL_ADDRESS: "glazunov2142@gmail.com"
      # Logger
      LOGGER_ERRORS_BUFFER_CAPACITY: "10"
      LOGGER_REQUESTS_BUFFER_CAPACITY: "10"
    command: ["sh", "-c", "./.ops/build/build_and_rotate.sh && ./streaming"]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "/data/storage/mongodb:/data/db"

  mongodb-client:
    build:
      context: .
      dockerfile: .ops/docker/mongoclient/Dockerfile
    depends_on:
      - mongodb
volumes:
  mongodb_data: